server:
  port: 8000
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3360/user-registration
#    username: root
#    password: fils1?
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
  username: root
  password: fils1?
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


